name: AuthX
version: '${project.version}'
main: io.aurora.AuthX
api-version: '1.19'

commands:
  authx:
    description: Setup and verify TOTP for your account
    usage: /authx <setup | verify | reload>
